version: "3.8"

services:
  backend:
    build: ./
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mysql
    command: ["/bin/sh", "./start.sh"]

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dlp_db:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - 3307:3306

volumes:
  dlp_db:
