# Generated by Django 5.0.3 on 2024-04-04 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LossPreventionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('pattern', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataLeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(max_length=255)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp_app.losspreventionpattern')),
            ],
        ),
    ]
