# Generated by Django 5.0.3 on 2024-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0002_remove_queue_delay_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='region',
            field=models.CharField(default='eu-north-1', max_length=255),
        ),
    ]
